name: Deploy Docs to Github Pages
on:
  push:
    branches:
      - v2
    paths:
      - "docs/**"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: cd docs && mkdocs gh-deploy --force